sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository ppa:jonathonf/texlive
  - sudo apt install texlive-full
  - sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
  - make all
